import type {ParameterSchemaSpec,ParameterPropertySpec,ValueSchemaSpec} from '@deepseek-ai/dsh-tools'
import type {EntityMotion,SimAction} from '../../sim-contract/src/index.ts'
import type {RobotOperations} from './operations.ts'
const required=(schema:ValueSchemaSpec):ParameterPropertySpec=>({...schema,required:true})
const text=(description:string):ValueSchemaSpec=>({type:'string',description})
const number=(description:string):ValueSchemaSpec=>({type:'number',description})
const array=(items:ValueSchemaSpec,description?:string):ValueSchemaSpec=>({type:'array',items,...description===undefined?{}:{description}})
const object=(properties:ParameterSchemaSpec,description?:string,additionalProperties=false):ValueSchemaSpec=>({type:'object',properties,additionalProperties,...description===undefined?{}:{description}})
const union=(variants:ValueSchemaSpec[]):ValueSchemaSpec=>variants.length===1?variants[0]!:{oneOf:variants as [ValueSchemaSpec,ValueSchemaSpec,...ValueSchemaSpec[]]}
const sceneId=required(text("Scene ID returned by scene_create / scene_inspect."))
const worldId=required(text("Explicit worldId returned by sim_open or sim_world_list; never use an implicit current Viewer world."))
const entityId=required(text("Stable entityId of the target entity in Scene. Identical robot models still have separate IDs."))
const jointNames=required(array(text("Actual joint name returned by robot_describe."),"Ordered joint-name array, aligned with every complete positions vector."))
const positions=required(array(number("Hinge joints use radians and slide joints use meters; follow robot_describe units."),"Complete target for each joint. Its length must match jointNames; the Provider validates the full vector once."))
const durationS=required(number("Action duration in seconds; must be greater than 0."))
const tolerance=number("Tolerance for measured joint-tracking error, in the corresponding joint's units; this is not a task-success flag.")
const settleTimeS=number("Time in seconds for holding/converging at the final target.")
const point=object({timeS:required(number("Seconds since action start. Trajectory times must increase strictly.")),positions})
const points=required(array(point,"Complete trajectory array: each time point supplies targets for every listed joint."))
const plan=object({planId:required(text("Planning-result ID.")),entityId,modelVersion:required(text("Robot model version at planning time.")),jointNames,points,collisionContextVersion:required(text("Relevant collision-context version.")),expectedGeneration:required({type:'integer',description:"worldGeneration at planning time."})},"Optional existing MotionPlan. The Provider checks model generation and relevant collision context.")
const kind=(value:string):ParameterPropertySpec=>({type:'string',const:value,required:true})
/** thrust 支持范围（按源执行器力律逐条核对）：不是所有 source actuator 都支持，其余明确 UNSUPPORTED。 */
const thrustChannelScope="Support only controller-mapped site actuators with stateless fixed gain and no bias/activation dynamics/plugin/refsite (actuator force=gain×ctrl). Reject other types explicitly rather than silently treating them as direct force channels."
const thrustN=required(number("Body-frame thrust in newtons along +Z. The source mapping must express this direction exactly or reject it. Units and limits come from the source actuator force law (fixed gain×site/gear, ctrlrange/forcerange); values beyond source authority are rejected, not silently clamped."+thrustChannelScope))
const thrustTorqueNm=array(number("Body-frame torques in N·m around x/y/z, in x/y/z order, referenced to the entity root rigid-body origin. No built-in hover or attitude control."),"Optional three values. Validate against source actuator authority and reject mappings that cannot express them exactly.")
const thrustDurationS=required(number("Body-thrust duration in seconds, greater than 0. Quantize by physics steps: count=max(1, round(durationS/dt)); actual duration=count×dt. Mutually exclusive with stepCount."))
/**
 * gait（四足步态）通道的真实范围：**两条路线分开说，不合并成"策略"**。
 *
 * 为什么单列：工具面曾把 gait 讲成"策略"（`robot_walk`＝"只运行资产已有且适用的**步态策略**"、
 * forward＝"已支持四足**策略**的前进意图"），而**默认路径**跑的是 `packages/sim-mujoco/python/gait.py`
 * 的**几何开环相位目标**（MuJoCo 与 Isaac 两个 worker 直接 import 同一份实现），返回体里也没有任何
 * "开环/无稳定器/不保证方向"的自述 ⇒ 合同不认 gait、文案说策略、通道是几何开环，三处各说各话。
 * 判定与证据：`bugfixHistory/VERIFY-ISAAC-GAIT-DRONE-20260926.md` §2.2-A18／§5 乙类；
 * 本机复算：`gait.targets()` 是 (t,forward,turn) 的纯函数，turn=0 时 ±forward 一个周期内的
 * thigh/calf 目标集合逐值相同（只有相位次序不同）⇒ 这条通道**连位移方向都不携带**。
 */
export const gaitChannelScope="The gait action has two separate routes; do not merge them as one policy. Without policy/packId, pass through to the Provider's geometric open-loop phase-target channel (packages/sim-mujoco/python/gait.py calibrate()/targets(): source MJCF planar two-link geometry plus phase; no policy weights, state estimation, stabilizer, or feedback). forward scales swing amplitude and phase order only; it is neither a speed target nor a displacement-direction command (measured forward=+0.6 produced net x=−0.0868m, backwards). With policy or packId, use the product policy route executePolicy → sim.execute(kind:\"control\"), where weights produce references. robot_describe gait.available=true establishes only that the first channel accepts targets after successful geometry calibration, not that the robot walks. Determine walking from displacement measurements, never availability alone."
/** 只映射现有EntityMotion，不新增机器人类型系统。新增动作种类时这里必须同步编译。 */
const motionFields:Record<EntityMotion['kind'],ParameterSchemaSpec[]>={
 trajectory:[{kind:kind('trajectory'),entityId,jointNames,points,tolerance,settleTimeS,plan}],
 joint:[{kind:kind('joint'),entityId,jointNames,positions,durationS,tolerance,settleTimeS}],
 vehicle:[
  {kind:kind('vehicle'),entityId,speedMps:required(number("Target chassis linear speed in m/s. Negative reverses; zero injects no drive.")),steeringAngleRad:required(number("Virtual front-axle steering angle in radians. Positive turns left while moving forward; asset configuration converts rear steering.")),durationS},
  {kind:kind('vehicle'),entityId,speedMps:required(number("Target chassis linear speed in m/s.")),yawRateRadps:required(number("Explicit differential-drive yaw rate in rad/s; mutually exclusive with steeringAngleRad.")),durationS},
  {kind:kind('vehicle'),entityId,speedMps:required(number("Target chassis linear speed in m/s. Without steering, travel straight.")),durationS},
 ],
 lift:[
  {kind:kind('lift'),entityId,positionM:required(number("Absolute fork/lift position in meters, not an increment for this invocation.")),durationS,tolerance},
  {kind:kind('lift'),entityId,velocityMps:required(number("Lift velocity in m/s, combined with durationS to calculate the target; do not also supply positionM.")),durationS,tolerance},
 ],
 gripper:[{kind:kind('gripper'),entityId,widthM:required(number("Total target gripper opening width in meters; the actual mapping comes from asset controller.gripper.")),durationS,settleTimeS,tolerance}],
 tendon:[{kind:kind('tendon'),entityId,tendonNames:required(array(text("tendonActuators names returned by robot_describe, using source tendon names such as Shadow rh_FFJ0. These are not joint names; use joint for joint-level actuators. Accept only channels reported with controlMode=position after verifying fixed gain/bias relationships; reject custom force laws."),"At least one name, unique and aligned with lengths.")),lengths:required(array(number("Target tendon coordinates. For a fixed tendon this is Σ coef·q; rad/m units are in robot_describe tendonActuators.unit. The Provider converts ctrl=gear×target using source actuator gear and rejects source actuator ctrlrange violations. ctrlApplied reports the last actual write; holdReference reports the reference held after stopping."),"One value for each tendonNames entry.")),durationS,settleTimeS,tolerance}],
 gait:[{kind:kind('gait'),entityId,forward:required(number("Quadruped forward intent in [-1,1]. It scales swing amplitude and phase order only, not target speed or displacement direction. Positive and negative forward yield the same target set over one cycle with a different phase order. This channel is geometric open-loop; see robot_walk for its scope.")),turn:number("Quadruped turning intent in [-1,1], implemented by per-leg differential motion, not a yaw-rate target."),durationS,
   // ISAAC-14(b)／W23：策略身份**由调用方声明**，两种形态取一 —— 与既有 `policy_execute` 同口径（那边本来
   // 就要求调用方给 provider/modelId/revision）。**两者都不给 ⇒ 保持既有透传**（`kind:'gait'` 原样到 Provider），
   // 适配层**不按机型名硬映射**：身份来源不明时不猜，只透传。
   policy:object({provider:required(text("Policy source: modelscope|github|huggingface|packs, using the policy_execute contract.")),modelId:required(text("Policy ID, such as Improbable-AI/walk-these-ways.")),revision:required(text("Policy revision, such as a commit sha or master."))},"Optional explicit policy identity, mutually exclusive with packId. When supplied, use executePolicy → sim.execute(kind:control); otherwise preserve pass-through behavior."),
   packId:text("Optional capability-pack ID, such as unitree_go1. Read identity from packs/<packId>/policy/manifest.json weights.resolution, declared by the pack itself; do not hard-map model names in the adapter. Mutually exclusive with policy.")}],
 control:[{kind:kind('control'),entityId,jointNames,positions,stepCount:required({type:'integer',description:"Positive physical-step count for holding position-actuator references under a manual clock. No interpolation; this does not prove target arrival."})}],
 thrust:[
  {kind:kind('thrust'),entityId,thrustN,torqueNm:thrustTorqueNm,durationS:thrustDurationS},
  {kind:kind('thrust'),entityId,thrustN,torqueNm:thrustTorqueNm,stepCount:required({type:'integer',description:"Positive exact integer physical-step count under a manual clock, mutually exclusive with durationS (the other field must be omitted). Write command ctrl every step of the window, then write zero on completion/stop/close; supported force channels return exactly to zero."})},
 ],
}
const actionMetadata:ParameterSchemaSpec={actionId:required(text("Unique action ID. Retrying the same ID does not duplicate motion; never reuse it with different arguments.")),expectedGeneration:required({type:'integer',description:"worldGeneration returned by sim_open/robot_describe at request time. Pass it unchanged; do not substitute the latest generation."}),startStep:{type:'integer',description:"Optional future shared start step; every batch member writes on the same tick."}}
const entityMotion=union(Object.values(motionFields).flat().map(fields=>object(fields)))
const actions=(kinds:SimAction['kind'][]):ValueSchemaSpec=>union(kinds.flatMap(k=>k==='batch'?[object({...actionMetadata,kind:kind('batch'),motions:required(array(entityMotion,"One motion per entity, without duplicate entityId. Child motions contain no actionId/generation."))})]:motionFields[k].map(fields=>object({...actionMetadata,...fields}))))
const actionInput=(kinds:SimAction['kind'][],description:string,examples?:any):ParameterSchemaSpec=>({input:{...object({worldId,action:required(actions(kinds))},description),required:true,...examples?{examples}:{} }})
const representation=object({uri:required(text("URI of a local original or derived representation.")),mimeType:required(text("Actual MIME type.")),role:text("Representation role."),losses:array(text("Explicit content losses introduced during derivation."))})
const resource=object({resourceId:required(text("Resource ID.")),version:required({type:'integer',description:"Resource version."}),original:required(representation),representations:required(array(representation)),source:required(object({units:required(text("Original length units.")),upAxis:required({type:'string',enum:['X','Y','Z']}),handedness:required({type:'string',enum:['right','left']}),metersPerUnit:number("Scale converting source units into meters.")}))})
const transform=object({position:required(array(number("Meters."),"Three XYZ values in the right-handed Z-up frame.")),quaternion:required(array(number("Quaternion component."),"Four values in fixed [x,y,z,w] order.")),scale:required(array(number("Scale."),"Three XYZ values."))})
const component=object({},"Preserve the owning Provider's namespace fields.",true)
const entity=object({entityId,parentId:text("Optional parent entity ID."),name:required(text("Display name; it does not determine robot capability.")),transform:required(transform),resources:required(array(resource,"Ordinary resource references. A new native MJCF entity may use an empty array and specify the original through components.mujoco.sourcePath.")),components:required(object({visual:component,collision:component,rigidBody:component,articulation:component,controller:{...component,description:"Asset control mapping. For wheels, radiusM/wheelbaseM use meters, steering uses radians, and lift uses absolute meters. Drone thrust uses thrustActuator+torqueActuators(x/y/z). The mapped entity may have no joints; all four actuators must be stateless fixed-gain site actuators without bias/activation dynamics/plugin/refsite. Preserve generic and custom policy fields."},sensor:component,mujoco:object({sourcePath:text("Absolute local path to the original MJCF/URDF."),xml:text("Explicit native model text.")},"MuJoCo native representation, not registration or eligibility state.",true),isaac:component},"Optional physics/control/sensor components and native-format namespaces.",true))},"Create an ordinary robot entity. Existing entities need only entityId; do not generate registration or Chinese-language memory.")
const stop=object({worldId,entityIds:array(text("entityId to stop."),"Omission stops the entire world."),actionId:text("Cancel only control still owned by this known action, without affecting actions that subsequently took over."),expectedGeneration:{type:'integer',description:"Action/workflow cleanup must carry the original worldGeneration. A stale stop does not affect a newer generation."}},"Stop immediately without waiting for an LLM to generate another plan.")
const worldOptions=object({worldId:text("Explicit new world ID; omission lets the Provider generate it."),timestepS:number("Physics timestep in seconds."),realtimeFactor:number("Realtime multiplier."),frameRateHz:number("Projection frame rate in Hz, not the physics-step frequency."),ground:{type:'boolean',description:"Whether to add the default ground."},startPaused:{type:'boolean',description:"Atomically pause before the first exposed physics step for controller preparation. Preserve clock, gravity, and model state. Omission retains normal startup; resume the same world with sim_set_paused. Unsupported providers reject this option explicitly."},clock:{type:'string',enum:['realtime','manual'],description:"Defaults to realtime. With manual, only the Provider's single clock advances during explicit actions, supporting policies sampled per physics step. Accept only realtime/manual; reject other values. A Provider with no advancing action channel (Newton) accepts manual but honestly remains frozen and reports manualClockAdvance=UNSUPPORTED_CAPABILITY instead of pretending to step."}},"World-creation options. The engine is a Host-level choice determined by startup --engine/LYAPUNOV_SIM_ENGINE or a UI-saved preference. This tool has no engine argument and cannot switch engines per world. The receipt is this world's WorldHandle; engineId/engineVersion identify the engine actually used. capabilities contains only a Provider's own report: Newton currently reports supported/unsupported/notes at ready. Without a provider report, omit the field instead of inventing defaults.")
const jointExample=[{worldId:'world-1',action:{actionId:'move-1',expectedGeneration:1,kind:'joint',entityId:'arm-a',jointNames:['j1','j2','j3'],positions:[.3,-.2,.1],durationS:.5}}]
/** 采集/导出的落盘目录：相对路径按会话任务工作区解析（与 bash 一致），也可以给绝对路径。 */
const outputDir=required(text("Output directory. Resolve relative paths against the current session's task workspace, as bash/the terminal does, or accept an absolute path. The receipt's outputDir reports the absolute directory actually written."))
const width={type:'integer' as const,description:"Image width in pixels. When supplied, all cameras in this capture use this resolution."}
const height={type:'integer' as const,description:"Image height in pixels; must be supplied together with width."}
const geomGroups=array({type:'integer',description:"MuJoCo display group, valid values 0..5."},"Optional display groups. When explicitly supplied, RGB and depth render only these groups (collision-specific assets often put the arm in 3); omission uses engine defaults. Rendering only: collision and mass do not change. This is implemented only by MuJoCo. Isaac explicitly returns UNSUPPORTED because RTX capture has no display-group concept, rather than silently ignoring the field. Newton's rendering channel is unimplemented.")
const multiCameraNames=required(array(text("Named native camera in this world, listed by camera_list, such as wrist/head/overview."),"Nonempty and unique. Reject the entire request for any missing/duplicate name, without partial capture. Every camera shares the same physics step and frameId."))
const namedCamera=required(text("Named camera in this world, returned by camera_list. Reject a missing camera or stale world generation."))
/**
 * 相机族按 Provider 的**真实**范围（逐条与两侧实现同源，2026-09-22 真机复核）：
 *  · `camera_list`／`camera_adjust`：Isaac provider 已真实接线（`sim-isaac/src/provider.ts` 转发
 *    `camera_list`／`camera_adjust`；真机 rendering:none 下 `camera_list` 回 `status:"AVAILABLE"` 的命名相机、
 *    `camera_adjust` 回真实 override 回执），不再是"Isaac 返回 UNSUPPORTED"；
 *  · `camera_capture_multi`：Isaac 需要 `rendering:rtx`；未启动 RTX 时按 `SENSOR_UNAVAILABLE`
 *    （"当前Profile未启动RTX；传感器采集需要rendering:rtx"）阶段化拒绝，不假装可用；
 *  · Newton 切片没有渲染/相机通道（`UNSUPPORTED_CAPABILITY`）。
 */
export const cameraFamilyScope="MuJoCo and Isaac implement camera_list/camera_capture_multi/camera_adjust. Isaac camera_list and camera_adjust also work with rendering:none, as verified on the actual engine. camera_capture_multi requires rendering:rtx and returns staged SENSOR_UNAVAILABLE without RTX startup. The Newton slice has no rendering/camera channel and returns UNSUPPORTED_CAPABILITY. Report unavailable operations explicitly with reasons, never as achievable."
/**
 * 标注/数据集导出两个入口的 Provider 范围（2026-09-26 起 Isaac 侧也真实实现，与盘上代码同源）：
 *  · `camera_project_annotation`：Isaac 用**被引用 capture** 的真实深度 npy，或（未给 captureId 时）
 *    本步新鲜渲染的深度；未启动 RTX 且没给 captureId 时按 `SENSOR_UNAVAILABLE` 阶段化拒绝，
 *    captureId 不存在/属于旧代次/相机不在该 capture 里各有结构化错误码；
 *  · `camera_dataset_export`：消费 Isaac 已记录的真实采集（capture／capture_multi 回执里的 captureId）。
 *  Newton 切片没有渲染/相机通道（`UNSUPPORTED_CAPABILITY`）。
 */
export const cameraAnalysisScope="MuJoCo and Isaac implement these two camera operations. Isaac camera_project_annotation uses actual depth npy from the referenced capture, or fresh depth rendered at this step if captureId is omitted. Without RTX and without captureId, return staged SENSOR_UNAVAILABLE. Missing/stale-generation captureIds or a camera absent from the capture each have structured error codes. camera_dataset_export uses actual recorded capture/capture_multi captureIds. The Newton slice has no rendering/camera channel and returns UNSUPPORTED_CAPABILITY. Reject unavailable operations explicitly with reasons, never reporting them as achievable."
/** 单相机采集（sensor_capture）的 Provider 范围：MuJoCo/Isaac 都实现，其中 geomGroups 只由 MuJoCo 消费。 */
export const singleCaptureScope="MuJoCo and Isaac implement single-camera capture; Isaac requires rendering:rtx. Only MuJoCo consumes geomGroups, and Isaac rejects an explicit geomGroups field. Newton has no capture channel (UNSUPPORTED_CAPABILITY)."
const cameraPoseM=array(number("Reference-frame coordinate in meters."),"Three XYZ values, right-handed Z-up, interpreted by referenceFrame: world means world coordinates and parent means coordinates local to parentBodyName. May be supplied alone. Omission inherits only an existing explicit value in that same frame or the frame's current source value, for a partial update.")
const cameraQuaternionXyzw=array(number("Quaternion component."),"Four values in fixed [x,y,z,w] order. Prior normalization is not required; the Provider normalizes by magnitude for rendering. Interpret through referenceFrame: world orientation or parentBodyName-local orientation. May be supplied alone; omission inherits only an existing explicit value in the same frame or its current source orientation.")
const referenceFrame={type:'string' as const,enum:['world','parent'],description:"Pose reference frame: world (default), where positionM/quaternionXyzw are explicitly fixed world poses and do not follow joint movement; or parent, local to the camera's owning body and transformed through that body's current FK each frame, recommended for mounted-camera installation offsets. Changing an existing override's frame performs explicit safe conversion at current FK and reports frameConverted/convertedFromFrame without silently mixing coordinates."}
const fovyDeg=number("Vertical field of view in degrees, with 0<fovy<180. May be supplied alone; omission uses the current override or source FOV. Affects only this camera's temporary override, not source MJCF/Scene. FOV-only without explicit pose fields does not freeze pose; a mounted camera keeps following its parent body.")
const annotationPixel=required(array({type:'integer',description:"Integer pixel column u or row v, inside image bounds."},"Two integers [u,v]: column u in 0..width-1 and row v in 0..height-1, using pixel-center convention. Reject out-of-bounds or noninteger values."))
const robotConfigurationIdentity={worldId,sceneId,entityId,expectedRevision:required({type:'integer' as const,description:"Current revision from scene_inspect; the current world must already be synchronized to it."}),expectedGeneration:actionMetadata.expectedGeneration!}
const baseAnchor=object({entityId:text("Omission uses a world anchor; supplying it selects another actual entity."),bodyName:text("Actual body in the target entity, required with entityId. Read it from robot_describe or camera_list bodies."),positionM:required(array(number("Meters."),"World-anchor XYZ, or local XYZ of the specified target body.")),quaternionXyzw:required(array(number("Quaternion."),"Normalized xyzw quaternion in the same reference frame as positionM."))},"Target installation pose of the root-base origin, not a visual parentId.")
/** 每个稳定operation仍使用原input包装；schema只在DSH边界描述/验证结构。 */
export const robotToolParameters:Record<keyof RobotOperations,ParameterSchemaSpec>={
 sim_open:{input:required(object({sceneId,options:worldOptions}))},
 sim_world_list:{},
 sim_sync:{input:required(object({sceneId,worldId}))},
 sim_set_paused:{input:required(object({worldId,paused:required({type:'boolean',description:"true pauses the actual physics clock; false resumes it."}),expectedGeneration:required({type:'integer',description:"Exact current world generation; reject a stale generation."})}))},
 sim_reset:{input:required(object({sceneId,worldId,expectedRevision:robotConfigurationIdentity.expectedRevision,expectedGeneration:robotConfigurationIdentity.expectedGeneration},"Stop all actions in the current world, then rebuild natively from the same Scene's initial state. Do not edit Scene. Reset every instance and base together, preserving this world's options."))},
 sim_close:{input:required(object({worldId}))},
 robot_load:{input:required(union([object({worldId,sceneId,entityId}),object({worldId,sceneId,entity:required(entity),entityId:text("When entity is supplied, use entity.entityId.")})]))},
 robot_describe:{input:required(object({worldId,entityId}))},
 robot_presets:{input:required(object(robotConfigurationIdentity,"Read this instance's native sites/bodies, uncovered MJCF/USD camera presets, and user Scene installation baseline. Without a preset, return actual candidates/reasons instead of guessing generic offsets."))},
 robot_set_tcp:{input:required(union([
  object({...robotConfigurationIdentity,tcp:required(object({body:required(text("Actual link name in nativeBodies.")),site:required(text("Real nativeSites site belonging to this body; use the complete local pose supplied by the compiler."))}))}),
  object({...robotConfigurationIdentity,tcp:required(object({body:required(text("Actual link in nativeBodies. Explicitly choose that body's origin or a local offset.")),offsetM:array(number("Meters."),"Body-local XYZ; omission uses the origin."),quaternionXyzw:array(number("Quaternion."),"Body-local normalized xyzw; omission uses the identity orientation.")}))}),
  object({...robotConfigurationIdentity,clear:required({type:'boolean',const:true})}),
 ]))},
 robot_set_base:{input:required(object({...robotConfigurationIdentity,base:required(union([
  object({mode:required({type:'string',enum:['source','free']}),bodyName:required(text("Actual root-base name, not an internal rotating link."))}),
  object({mode:required({type:'string',const:'fixed'}),bodyName:required(text("Actual root-base name.")),target:required(baseAnchor)}),
 ]))}))},
 robot_state:{input:required(object({worldId,entityId:text("Optional single-entity filter; omission reads every entity."),contacts:{type:'boolean',description:"Include actual contact observations."}}))},
 robot_move:actionInput(['joint','trajectory','batch','vehicle','lift','gripper','gait','thrust','tendon'],"Prefer joint or a complete trajectory. Use thrust for body thrust/torque (a jointless entity may still have a thrust mapping; only stateless fixed-gain site actuators without bias/activation/plugin/refsite are supported, with explicit rejection otherwise). Use tendon for source fixed-tendon Σ coef·q coordinates; closing is not grasp success. See robot_walk for quadruped geometric open-loop phase targets, not policy inference. All actual actions still use the same sim.execute.",jointExample),
 joint_move:actionInput(['joint','lift'],"Partial joints or absolute/velocity lift motion.",jointExample),
 vehicle_drive:actionInput(['vehicle'],"Use SI vehicle semantics with separate speed and steering. Steering at zero speed does not add forward motion.",[{worldId:'world-1',action:{actionId:'drive-1',expectedGeneration:1,kind:'vehicle',entityId:'fork-a',speedMps:.3,steeringAngleRad:.2,durationS:2}}]),
 robot_gripper:actionInput(['gripper'],"Total gripper opening width in meters; closing is not grasp success.",[{worldId:'world-1',action:{actionId:'grip-1',expectedGeneration:1,kind:'gripper',entityId:'arm-a',widthM:.04,durationS:.5}}]),
 robot_walk:actionInput(['gait'],"Run the asset's existing quadruped gait channel, using geometric open-loop phase targets rather than policy inference."+gaitChannelScope),
 sim_execute_batch:actionInput(['batch'],"One outer actionId/generation; entities in motions share a start step.",[{worldId:'world-1',action:{actionId:'batch-1',expectedGeneration:1,kind:'batch',motions:[{kind:'joint',entityId:'arm-a',jointNames:['j1'],positions:[.2],durationS:1},{kind:'joint',entityId:'arm-b',jointNames:['j1'],positions:[-.2],durationS:1}]}}]),
 robot_stop:{input:required(stop)},sim_stop:{input:required(stop)},
 sim_action_receipt:{input:required(object({worldId,actionId:required(text("Original accepted actionId."))}))},
 sim_assist:{input:required(union([object({worldId,mode:{type:'string',const:'attach',required:true},expectedGeneration:actionMetadata.expectedGeneration!,objectId:required(text("Object ID for explicit assisted attachment.")),robotId:required(text("Robot entity ID.")),anchorBody:required(text("Anchor-body name in the native model."))}),object({worldId,mode:{type:'string',const:'release',required:true},expectedGeneration:actionMetadata.expectedGeneration!,objectId:required(text("Object ID whose assistance is released.")),robotId:text("Optional."),anchorBody:text("Optional.")})]))},
 sensor_capture:{input:required(object({worldId,outputDir,cameraName:text("Optional native camera name."),width:{type:'integer',description:"Image width in pixels."},height:{type:'integer',description:"Image height in pixels."},geomGroups},singleCaptureScope))},
 camera_list:{input:required(object({worldId},"Read final actual poses for all named cameras (worldFromCamera; FOV-only does not freeze pose and mounted cameras follow parent-body FK), source poses (sourceWorldFromCamera), vertical FOV (fovyDeg/sourceFovyDeg), and actual effective K (intrinsics.fx/fy/cx/cy/width/height, with intrinsicsSource=fovy|mjcf|engine-intrinsics). For engine-intrinsics, return appliedIntrinsicsPx declarations and engineIntrinsics engine readings; unmodeled distortion reports distortionModeled=false and echoes distortionDeclared. Also return owning parentBodyName, override referenceFrame, and explicitly overridden fields. Do not modify models."+cameraFamilyScope))},
 camera_capture_multi:{input:required(object({worldId,outputDir,cameraNames:multiCameraNames,width,height,geomGroups},"Capture RGB and depth in meters for all named cameras at the same physics step, sharing stepIndex/simTime/frameId/sceneRevision. Return per-camera complete pinhole calibration (fx/fy/cx/cy/fovy/worldFromCamera/resolution and intrinsicsSource identifying K). Declared K is the K actually used for rendering, preserving nonsquare pixels and off-center principal points. Do not advance the physics clock additionally. Reject the entire call for any invalid argument."+cameraFamilyScope))},
 camera_adjust:{input:required(object({worldId,cameraName:namedCamera,referenceFrame,positionM:cameraPoseM,quaternionXyzw:cameraQuaternionXyzw,fovyDeg,expectedGeneration:required({type:'integer',description:"worldGeneration returned by sim_world_list/robot_describe at request time. Pass unchanged; explicitly reject stale generations without replacing them with the latest."}),clear:{type:'boolean',description:"true clears this camera's temporary override and restores source pose/FOV. Mutually exclusive with positionM/quaternionXyzw/fovyDeg."},width,height},"Create or partially update a temporary named-camera override in the current world. Supply positionM/quaternionXyzw/fovyDeg separately or together; non-clear requests need at least one. Omitted pose fields inherit only existing explicit values in the same referenceFrame or that frame's current source values. clear=true clears and is mutually exclusive with those fields. referenceFrame defaults to world for explicitly fixed world poses; mounted-camera offsets use parent, local to parentBodyName and transformed by current parent-body FK each frame. FOV-only without explicit pose does not freeze it. Convert frame changes explicitly and safely. Affect only future capture/calibration, never source MJCF/Scene. Translation alone or width/height alone does not change K; intrinsicsAtReferenceResolution reports effective K at the call's resolution (640×480 if omitted). For existing K, fovyDeg rescales focal lengths only (fovyApplied=intrinsic-focal-rescale; fy'=H_c/(2tan(fovy/2)), fx' scales proportionally), preserving the principal point and never forcing fx=fy. Pure-fovy cameras retain whole-image vertical FOV. Return complete position/quaternion/fovy/intrinsics, final actual worldFromCamera, parentBodyName/referenceFrame, override=true/worldGeneration. clear receipts include cleared/calibration; sim_close/sim_sync or clear removes overrides."+cameraFamilyScope))},
 camera_project_annotation:{input:required(object({worldId,cameraName:namedCamera,pixel:annotationPixel,depthM:number("Actual axial depth in meters along the optical axis at this pixel. An explicit value must agree with real rendering within tolerance or be rejected; never fabricate depth to invent a world point. Omission uses measured depth from the referenced capture or this step's actual render."),captureId:text("Optional captureId returned by camera_capture_multi/camera_capture, ensuring pixel/depth share capture and frame provenance. Reject a camera absent from that capture."),width,height,geomGroups},"Annotate camera/world coordinates from pixels and real depth. Return worldPointM/cameraPointM, frameId, captureId, and calibration provenance for reprojection to the original pixel. Reject boundary pixels, background/invalid depth, and depth mismatches. Depth ray mapping differs from RGB pixel convention at a measured subpixel scale (about ≤0.5 px); integer-pixel depth lookup gives world-point differences roughly ≤5 mm at 3 m."+cameraAnalysisScope))},
 camera_dataset_export:{input:required(object({worldId,outputDir,captureIds:required(array(text("Existing captureId in this world, returned by camera_capture_multi/camera_capture."),"At least one unique captureId. Array order determines dataset frame order; IDs from other worlds are forbidden."))},"Export actual multi-view capture into a self-contained training dataset: samples.jsonl per frame/per camera, per-camera calibration, annotation references, and actual PNG/NPY copies. Cameras in one frame share step/frameId; never combine unsynchronized data as synchronized captures."+cameraAnalysisScope))},
}
