import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync,writeFileSync,mkdirSync,copyFileSync,mkdtempSync,rmSync} from 'node:fs'
import {join,dirname,resolve} from 'node:path'
import {tmpdir} from 'node:os'
import {spawnSync} from 'node:child_process'
import {createHash} from 'node:crypto'
import {applySignedGuestOwnProviderPatch,verifiedGuestOwnProviderComposition} from './guest-own-provider-patch.mjs'
const root=resolve(import.meta.dirname,'..'),source=process.env.GUEST_OWN_PROVIDER_TEST_SDK??join(root,'.upstream/deepseek-harness-20260911-candidate'),manifestPath='packages/desktop/patches/dsh-guest-own-provider.json',oldManifestPath='packages/desktop/patches/dsh-guest-presentation-227-to-d756.json'
const manifest=JSON.parse(readFileSync(join(root,manifestPath),'utf8')),artifacts=[manifestPath,oldManifestPath,manifest.patch,manifest.precursorFullPatch,...manifest.dependencies.map(row=>row.file)]
const hash=path=>createHash('sha256').update(readFileSync(path)).digest('hex')
function fixture(){const dir=mkdtempSync(join(tmpdir(),'lyapunov-guest-own-patch-')),product=join(dir,'product'),sdk=join(dir,'sdk');for(const file of artifacts){mkdirSync(dirname(join(product,file)),{recursive:true});copyFileSync(join(root,file),join(product,file))}for(const row of manifest.files){mkdirSync(dirname(join(sdk,row.path)),{recursive:true});copyFileSync(join(source,row.path),join(sdk,row.path))}const snapshot=()=>Object.fromEntries(manifest.files.map(row=>[row.path,hash(join(sdk,row.path))]));const applied=verifiedGuestOwnProviderComposition(product,sdk);if(applied){const reverse=spawnSync('git',['-C',sdk,'apply','--reverse',join(product,manifest.patch)],{encoding:'utf8'});assert.equal(reverse.status,0,reverse.stderr)}return{dir,product,sdk,snapshot,patch:{file:join(product,manifest.patch),package:'@deepseek-ai/dsh-llm-pi-ai'},close:()=>rmSync(dir,{recursive:true,force:true})}}
test('已签d756真实Own/Root组合check→apply→完整post与第二次字节幂等',()=>{const b=fixture();try{assert.equal(applySignedGuestOwnProviderPatch(b.product,b.sdk,b.patch).status,'applied');const after=b.snapshot();assert.equal(applySignedGuestOwnProviderPatch(b.product,b.sdk,b.patch).status,'already-applied');assert.deepEqual(b.snapshot(),after)}finally{b.close()}})
test('改原生adapter任意字节拒且没有部分重写',()=>{const b=fixture();try{const path=join(b.sdk,'packages/llm/llm-pi-ai/src/adapter.ts');writeFileSync(path,readFileSync(path,'utf8')+'\n// unknown source fixture\n');const before=b.snapshot();assert.throws(()=>applySignedGuestOwnProviderPatch(b.product,b.sdk,b.patch),/未知或混合/);assert.deepEqual(b.snapshot(),before)}finally{b.close()}})
test('改未被增量触及的旧d756完整type也拒且无重写',()=>{const b=fixture();try{const path=join(b.sdk,'packages/api/session-controller/src/types.ts');writeFileSync(path,readFileSync(path,'utf8')+'\n// unknown composed type\n');const before=b.snapshot();assert.throws(()=>applySignedGuestOwnProviderPatch(b.product,b.sdk,b.patch),/未知或混合/);assert.deepEqual(b.snapshot(),before)}finally{b.close()}})
test('缺原生源码拒不借exists豁免',()=>{const b=fixture();try{rmSync(join(b.sdk,'packages/llm/llm-pi-ai/src/config.ts'));assert.throws(()=>applySignedGuestOwnProviderPatch(b.product,b.sdk,b.patch))}finally{b.close()}})
for(const artifact of artifacts)test('受签artifact改字拒：'+artifact,()=>{const b=fixture();try{const path=join(b.product,artifact);writeFileSync(path,readFileSync(path,'utf8')+'\n');const before=b.snapshot();assert.throws(()=>applySignedGuestOwnProviderPatch(b.product,b.sdk,b.patch),/签名/);assert.deepEqual(b.snapshot(),before)}finally{b.close()}})
test('只应用一个合法hunk仍是混合态，拒且不覆写其余合法旧源码',()=>{const b=fixture();try{const path='packages/llm/llm-pi-ai/src/auth.ts';copyFileSync(join(source,path),join(b.sdk,path));const before=b.snapshot();assert.throws(()=>applySignedGuestOwnProviderPatch(b.product,b.sdk,b.patch),/未知或混合/);assert.deepEqual(b.snapshot(),before)}finally{b.close()}})
