import {useEffect,useRef,useState} from 'react'
import type {Entity,Frame,SceneSnapshot,WorldHandle} from '../../lyapunov-contracts/src/types.ts'
import type {Translate} from './entity-editor.tsx'
import {physicsFacts,type PhysicsUpdateInput,type PhysicsBindInput} from './entity-physics.ts'
import {collisionBindingParameters,physicsBindingControlKey,bindingMotionChecked,scopedBindingMotion,DEFAULT_COLLISION_BINDING_SETTINGS,FULL_POINT_CLOUD_SETTINGS,FULL_POINT_CLOUD_SURFACE_SETTINGS,type CollisionBindingSettings,type ResourcePhysicsProgress} from './physics-binding-settings.ts'
import type {ResourcePhysicalizationRequest} from '../../scene-kit/src/resources.ts'
import {physicalizationBudgets,type PhysicalizationBudgetOptions} from '../../scene-kit/src/physicalization-parameters.ts'

export interface PhysicsRecoveryResource {ref:{resourceId:string;version:number};parsed?:{kind?:string};physicalizationRequest?:ResourcePhysicalizationRequest;physicalization?:ResourcePhysicsProgress&PhysicalizationBudgetOptions}
/** 实例冻结的请求优先，其后同版本资源请求/真实派生；跨资源和版本的读回不能初始化恢复。 */
export function physicsRecoveryOptions(owner:Entity|undefined,resource?:PhysicsRecoveryResource,progress?:ResourcePhysicsProgress):PhysicalizationBudgetOptions&{usage:PhysicsBindInput['usage'];strategy:CollisionBindingSettings['strategy']}{
 const ref=owner?.resources[0],same=ref&&resource?.ref.resourceId===ref.resourceId&&resource.ref.version===ref.version?resource:undefined
 const raw=owner?.components.physicsBinding as ({resourceId?:string;version?:number;usage?:string;strategy?:string}&PhysicalizationBudgetOptions)|undefined
 const binding=ref&&raw?.resourceId===ref.resourceId&&raw.version===ref.version?raw:undefined
 const request=same?.physicalizationRequest&&typeof same.physicalizationRequest==='object'?same.physicalizationRequest:undefined
 const physicalization=progress??same?.physicalization
 const usage=[binding?.usage,request?.usage,physicalization?.usage].find(value=>['dynamic','static','environment'].includes(String(value))) as PhysicsBindInput['usage']|undefined
 const strategy=[binding?.strategy,request?.strategy,physicalization?.strategy].find(value=>['auto','voxel_boxes','triangle_mesh','convex_hull','coacd','sdf'].includes(String(value))) as CollisionBindingSettings['strategy']|undefined
 return {...physicalizationBudgets(request??physicalization),...physicalizationBudgets(binding),usage:usage??(owner?.components.visual?.kind==='splat'?'environment':'dynamic'),strategy:strategy??'auto'}
}
function recoverySettings(options:ReturnType<typeof physicsRecoveryOptions>):CollisionBindingSettings{
 return {...DEFAULT_COLLISION_BINDING_SETTINGS,strategy:options.strategy,precision:options.voxelSizeM===undefined?'auto':'explicit',voxelSizeM:options.voxelSizeM??DEFAULT_COLLISION_BINDING_SETTINGS.voxelSizeM,maxBoxes:options.maxBoxes??DEFAULT_COLLISION_BINDING_SETTINGS.maxBoxes,maxOccupiedVoxels:options.maxOccupiedVoxels??DEFAULT_COLLISION_BINDING_SETTINGS.maxOccupiedVoxels,fullPointCloud:options.pointCloudTiling!==undefined}
}

export function PhysicsControls({scene,selected,world,frame,tr,disabled=false,update,bind,openLibrary,readProgress,progressIdentity,resource}:{scene:SceneSnapshot;selected:string;world?:WorldHandle;frame?:Frame;tr:Translate;disabled?:boolean;update:(input:PhysicsUpdateInput)=>Promise<unknown>;bind:(input:PhysicsBindInput,signal?:AbortSignal)=>Promise<unknown>;openLibrary:()=>void;readProgress?:(resourceId:string,version:number,signal:AbortSignal)=>Promise<ResourcePhysicsProgress|undefined>;progressIdentity?:string;resource?:PhysicsRecoveryResource}){
 const facts=physicsFacts(scene,selected,world,frame),owner=facts.owner
 const key=physicsBindingControlKey(scene.sceneId,owner?.entityId)
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[progressReadback,setProgressReadback]=useState<{key:string;value:ResourcePhysicsProgress|undefined}>(),bindingAbort=useRef<AbortController>()
 const recoveryKey=JSON.stringify([key,progressIdentity,owner?.resources[0]?.resourceId,owner?.resources[0]?.version]),progress=progressReadback?.key===recoveryKey?progressReadback.value:undefined,recovered=physicsRecoveryOptions(owner,resource,progress)
 const [usageDraft,setUsageDraft]=useState<{key:string;value:PhysicsBindInput['usage']}>(),[settingsDraft,setSettingsDraft]=useState<{key:string;value:CollisionBindingSettings}>()
 const usage=usageDraft?.key===recoveryKey?usageDraft.value:recovered.usage,settings=settingsDraft?.key===recoveryKey?settingsDraft.value:recoverySettings(recovered)
 const setUsage=(value:PhysicsBindInput['usage'])=>setUsageDraft({key:recoveryKey,value})
 const setSettings=(value:CollisionBindingSettings|((current:CollisionBindingSettings)=>CollisionBindingSettings))=>setSettingsDraft({key:recoveryKey,value:typeof value==='function'?value(settings):value})
 const [fixWhenBinding,setFixWhenBinding]=useState({key,fixed:false})
 const [mass,setMass]=useState({text:facts.massKg===undefined?'':String(facts.massKg),revision:scene.revision,dirty:false})
 const ref=owner?.resources[0]
 useEffect(()=>{let alive=true;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined
  setProgressReadback(undefined)
  if(readProgress&&ref){const poll=async()=>{let pending=false;try{const value=await readProgress(ref.resourceId,ref.version,controller.signal);pending=value?.status==='pending';if(alive)setProgressReadback({key:recoveryKey,value})}catch{}finally{if(alive&&(busy||pending))timer=setTimeout(poll,500)}};void poll()}
  return()=>{alive=false;controller.abort();if(timer)clearTimeout(timer)}
 },[busy,key,ref?.resourceId,ref?.version,progressIdentity])
 useEffect(()=>()=>bindingAbort.current?.abort(),[key,progressIdentity,ref?.resourceId,ref?.version])
 useEffect(()=>{setMass({text:facts.massKg===undefined?'':String(facts.massKg),revision:scene.revision,dirty:false});setFixWhenBinding({key,fixed:false});setError('')},[key])
 useEffect(()=>{setMass(value=>value.dirty?value:{text:facts.massKg===undefined?'':String(facts.massKg),revision:scene.revision,dirty:false})},[scene.revision,facts.massKg])
 const run=async(fn:()=>Promise<unknown>,clearMass=false)=>{setBusy(true);setError('');try{await fn();if(clearMass)setMass(value=>({...value,dirty:false}))}catch(value){setError(value instanceof Error?value.message:String(value))}finally{setBusy(false)}}
 if(!owner)return null
 const blocked=disabled||busy,positiveMass=mass.text.trim()!==''&&Number.isFinite(Number(mass.text))&&Number(mass.text)>0
 const write=(values:Omit<PhysicsUpdateInput,'sceneId'|'entityId'|'expectedRevision'>,revision=scene.revision)=>run(()=>update({sceneId:scene.sceneId,entityId:owner.entityId,expectedRevision:revision,...values}),values.massKg!==undefined)
 const bindingAllowed=!facts.native&&['mesh','group','splat'].includes(String(owner.components.visual?.kind))&&owner.resources.length>0
 const beginBind=()=>{const controller=new AbortController();bindingAbort.current=controller;return run(async()=>{try{const parameters=settingsDraft?.key===recoveryKey?{...physicalizationBudgets(recovered),...collisionBindingParameters(settings,usage)}:physicalizationBudgets(recovered);if(settingsDraft?.key===recoveryKey&&!settings.fullPointCloud)delete parameters.pointCloudTiling;if(settingsDraft?.key===recoveryKey&&settings.precision==='auto')delete parameters.voxelSizeM;return await bind({sceneId:scene.sceneId,entityId:owner.entityId,expectedRevision:scene.revision,usage,strategy:settings.strategy,...parameters,...scopedBindingMotion(fixWhenBinding,key)},controller.signal)}finally{if(bindingAbort.current===controller)bindingAbort.current=undefined}})}
 const yes=(value:boolean)=>value?tr('启用','Enabled'):tr('关闭','Disabled')
 const measured=facts.measured
 const knownDepths=(facts.overlap?.pairs??[]).flatMap(pair=>pair.depthStatus!=='UNKNOWN'&&typeof pair.depthM==='number'&&Number.isFinite(pair.depthM)&&pair.depthM>=0?[pair.depthM]:[])
 const unknownDepths=(facts.overlap?.pairs.length??0)-knownDepths.length
 const overlapDepth=knownDepths.length?unknownDepths?tr(`已测对的最大穿入 ${Math.max(0,...knownDepths).toFixed(5)} m；其余 ${unknownDepths} 对深度未知。`,`Maximum depth among measured pairs ${Math.max(0,...knownDepths).toFixed(5)} m; depth unknown for ${unknownDepths} other pairs.`):tr(`最大穿入 ${Math.max(0,...knownDepths).toFixed(5)} m。`,`Maximum depth ${Math.max(0,...knownDepths).toFixed(5)} m.`):tr('深度未知。','Depth unknown.')
 return <fieldset className="lya-property-editor" data-testid="entity-physics-controls" data-physics-owner={owner.entityId} aria-busy={busy}><legend>{tr('物理状态与操作','Physics state and controls')}</legend>
  {owner.entityId!==selected&&<p className="lya-help">{tr('所选节点属于物理实例：','Selected node belongs to physics instance: ')}{owner.name}</p>}
  <p className="lya-help" data-testid="declared-physics-state">{tr('场景配置：','Scene configuration: ')}{facts.native?tr('原生本体','Native model'):facts.type==='dynamic'?tr('动态物体','Dynamic body'):facts.type==='static'?tr('固定物体','Fixed body'):tr('尚未绑定物理','Physics not bound')} · {tr('质量：','Mass: ')}{facts.massKg===undefined?'—':`${facts.massKg} kg`} · {tr('重力：','Gravity: ')}{facts.native||!facts.hasCollider?'—':yes(facts.gravityEnabled)} · {tr('碰撞：','Collision: ')}{facts.hasCollider?yes(facts.collisionEnabled):facts.native?tr('由原生模型声明','Native model declaration'):tr('无碰撞声明','No collider declaration')}</p>
  {facts.binding&&<p className="lya-help">{tr('碰撞来源：','Collider source: ')}{facts.binding.resourceId} · v{facts.binding.version} · {facts.binding.status}</p>}
  <p className="lya-help" data-testid="native-physics-state">{tr('当前引擎：','Current engine: ')}{!facts.current?tr('等待同版本世界与物理帧','Waiting for a matching world and physics frame'):measured?<>{measured.dynamic?tr('动态','Dynamic'):tr('固定','Fixed')} · {tr('质量：','Mass: ')}{measured.massKg===null?'—':`${measured.massKg} kg`} · {tr('重力：','Gravity: ')}{yes(measured.gravityEnabled)} · {tr('碰撞：','Collision: ')}{yes(measured.collisionEnabled)} · {measured.colliderCount} {tr('个真实形状','compiled shapes')}</>:facts.geoms?<>{facts.geoms.length} {tr('个真实形状','compiled shapes')} · {tr('启用碰撞：','Enabled collisions: ')}{facts.geoms.filter(g=>g.collisionEnabled===true).length} · {tr('质量与重力未读回','Mass and gravity not reported')}</>:tr('该实例的原生物理属性尚未读回','Native properties for this instance have not been reported')}</p>
  {facts.current&&frame&&<p className="lya-help">{world?.engineId} · g{frame.generation} · rev {frame.sceneRevision} · step {frame.stepIndex} · {tr('实际位置 m：','Observed position m: ')}{frame.entities.find(e=>e.entityId===owner.entityId)?.transform.position.map(v=>v.toFixed(3)).join(', ')??'—'}</p>}
  {facts.overlap&&<p data-testid="physics-initial-overlap" className={facts.overlap.status==='OVERLAP'?'lya-help lya-error':'lya-help'} role={facts.overlap.status==='OVERLAP'?'alert':'status'}>{facts.overlap.status==='OVERLAP'?<>{tr(`世界初始化检出 ${facts.overlap.pairs.length} 对实际重叠；`,`World initialization detected ${facts.overlap.pairs.length} overlapping pairs; `)}{overlapDepth}</>:facts.overlap.status==='CLEAR'?tr('这次世界初始化检查未检出实际重叠。','This world initialization check found no overlaps.'):tr('这次世界初始化的重叠状态尚未验证。','Overlap at this world initialization remains unverified.')} · step {facts.overlap.checkedAtStep}{facts.overlap.reason?` · ${facts.overlap.reason}`:''}</p>}
  {facts.native?<p className="lya-help">{tr('本体约束由原生模型定义；关节手调使用机器人面板的直接控制。','Native constraints are defined by the model; use direct joint controls in the robot panel.')}</p>:facts.hasCollider?<>
   <div className="lya-row"><button type="button" data-physics-action="fixed" disabled={blocked||facts.type!=='dynamic'&&!positiveMass} onClick={()=>void write(facts.type==='dynamic'?{type:'static'}:{type:'dynamic',massKg:Number(mass.text)},facts.type!=='dynamic'&&mass.dirty?mass.revision:scene.revision)}>{facts.type==='dynamic'?tr('固定物体','Fix body'):tr('解除固定并启用动态','Unfix and enable dynamics')}</button></div>
   <label className="lya-field-label"><input type="checkbox" aria-label={tr('启用物体重力','Enable body gravity')} checked={facts.gravityEnabled} disabled={blocked} onChange={event=>void write({gravityEnabled:event.target.checked})}/>{tr('启用重力（动态时生效）','Enable gravity (applies to dynamic bodies)')}</label>
   <label className="lya-field-label"><input type="checkbox" aria-label={tr('启用物体碰撞','Enable body collisions')} checked={facts.collisionEnabled} disabled={blocked} onChange={event=>void write({collisionEnabled:event.target.checked})}/>{tr('启用碰撞','Enable collisions')}</label>
   <label className="lya-field-label">{tr('动态质量 kg','Dynamic mass kg')}<input type="number" aria-label={tr('动态质量 kg','Dynamic mass kg')} min={.000001} step={.1} disabled={blocked} value={mass.text} onChange={event=>setMass(value=>({text:event.target.value,revision:value.dirty?value.revision:scene.revision,dirty:true}))}/></label>
   <div className="lya-row"><button type="button" disabled={blocked||facts.type!=='dynamic'||!positiveMass||!mass.dirty} onClick={()=>void write({massKg:Number(mass.text)},mass.revision)}>{tr('提交质量并同步','Apply mass and sync')}</button><button type="button" disabled={busy} onClick={()=>{setMass({text:facts.massKg===undefined?'':String(facts.massKg),revision:scene.revision,dirty:false});setError('')}}>{tr('读取当前质量','Reload current mass')}</button></div>
   {mass.dirty&&mass.revision!==scene.revision&&<p className="lya-help lya-warning">{tr(`质量草稿仍基于 rev ${mass.revision}；场景已更新到 rev ${scene.revision}。`,`The mass draft is based on rev ${mass.revision}; the scene is now at rev ${scene.revision}.`)}</p>}
   {facts.type==='static'&&<p className="lya-help">{tr('固定时保留动态质量和重力配置，解除固定后应用。','Fixed bodies retain their dynamic mass and gravity settings for unfixing.')}</p>}
   <p className="lya-help">{tr('显示与碰撞分别控制；关闭碰撞后动态物体仍可受重力运动。','Visibility and collision participation are separate; a dynamic body can still move under gravity when collisions are disabled.')}</p>
  </>:<>
   <p className="lya-help">{tr('这个实例尚无碰撞声明。生成并绑定后会保存场景版本并同步物理世界。','This instance has no collider declaration. Generating and binding saves a scene revision and synchronizes physics.')}</p>
   <select className="lya-wide" aria-label={tr('碰撞绑定用途','Collider binding usage')} value={usage} disabled={blocked} onChange={event=>setUsage(event.target.value as PhysicsBindInput['usage'])}><option value="dynamic">{tr('动态物体 · 受重力','Dynamic body · gravity')}</option><option value="static">{tr('固定物体','Fixed body')}</option><option value="environment">{tr('环境 · 静态表面','Environment · static surfaces')}</option></select>
   <label className="lya-field-label"><input type="checkbox" aria-label={tr('同时固定这个物体','Fix this body when binding')} checked={bindingMotionChecked(fixWhenBinding,key)} disabled={blocked} onChange={event=>setFixWhenBinding({key,fixed:event.target.checked})}/>{tr('同时固定这个物体（保留质量与重力设置）','Fix this body when binding (retain mass and gravity settings)')}</label>
   {facts.type==='dynamic'&&!bindingMotionChecked(fixWhenBinding,key)&&settings.strategy==='triangle_mesh'&&<p className="lya-help lya-warning">{tr('此实例仍为动态；Isaac静态三角拓扑要求明确固定。不勾选会保留动态配置。','This instance is still dynamic. Isaac static triangle topology requires explicitly fixing it; leaving this unchecked preserves its dynamic settings.')}</p>}
   <label className="lya-field-label">{tr('碰撞表示','Collider representation')}<select aria-label={tr('碰撞表示','Collider representation')} disabled={blocked} value={settings.strategy} onChange={event=>setSettings(value=>({...value,strategy:event.target.value as typeof settings.strategy,fullPointCloud:false}))}><option value="auto">{tr('自动：保留空腔','Auto: preserve cavities')}</option><option value="voxel_boxes">{tr('表面／点采样体素','Surface / sample voxels')}</option><option value="triangle_mesh">{tr('三角面：需适用引擎','Triangle mesh: compatible engine required')}</option><option value="convex_hull">{tr('凸包','Convex hull')}</option><option value="coacd">{tr('凸分解','Convex decomposition')}</option><option value="sdf">{tr('距离场','Distance field')}</option></select></label>
   <label className="lya-field-label">{tr('精度选择','Precision')}<select aria-label={tr('精度选择','Precision')} disabled={blocked} value={settings.precision} onChange={event=>setSettings(value=>({...value,precision:event.target.value as 'auto'|'explicit',fullPointCloud:false}))}><option value="auto">{tr('自动（不能暗粗化超过0.03m）','Auto (no silent coarsening beyond 0.03m)')}</option><option value="explicit">{tr('明确指定米制近似','Explicit metre approximation')}</option></select></label>
   {settings.precision==='explicit'&&<label className="lya-field-label">{tr('采样体素边长 m','Sample voxel pitch m')}<input aria-label={tr('采样体素边长 m','Sample voxel pitch m')} type="number" min={.000001} step={.01} disabled={blocked} value={settings.voxelSizeM} onChange={event=>setSettings(value=>({...value,voxelSizeM:Number(event.target.value)}))}/></label>}
   <label className="lya-field-label">{settings.fullPointCloud?tr('每分块盒数预算 ≤10000','Per-tile box budget ≤10000'):tr('整个资源盒数预算 ≤10000','Whole-resource box budget ≤10000')}<input aria-label={tr('碰撞盒数预算','Collider box budget')} type="number" min={1} max={10000} step={1} disabled={blocked} value={settings.maxBoxes} onChange={event=>setSettings(value=>({...value,maxBoxes:Number(event.target.value)}))}/></label>
   <label className="lya-field-label">{settings.fullPointCloud?tr('每分块占据格预算 ≤1000000','Per-tile occupied-cell budget ≤1000000'):tr('点云整体占据格预算 ≤1000000','Whole point-cloud occupancy budget ≤1000000')}<input aria-label={tr('点云占据格预算','Point-cloud occupancy budget')} type="number" min={1} max={1000000} step={1} disabled={blocked} value={settings.maxOccupiedVoxels} onChange={event=>setSettings(value=>({...value,maxOccupiedVoxels:Number(event.target.value)}))}/></label>
   {owner.components.visual?.kind==='splat'&&<div className="lya-row"><button type="button" disabled={blocked} onClick={()=>{setUsage('environment');setSettings({...FULL_POINT_CLOUD_SETTINGS})}}>{tr('全域0.1m采样体素盒','Full-source 0.1m sample boxes')}</button><button type="button" disabled={blocked} onClick={()=>{setUsage('environment');setSettings({...FULL_POINT_CLOUD_SURFACE_SETTINGS})}}>{tr('全域0.1m采样表面 · Isaac静态','Full-source 0.1m sample surface · Isaac static')}</button></div>}
   {settings.fullPointCloud&&<p className="lya-help" data-testid="full-point-cloud-limits">{tr(`全源采样：${settings.voxelSizeM}m是明确近似，非默认0.03m或原点云三角重建。64³cells空间块，工作集≤${settings.maxOccupiedVoxels}格；全域≤2M格／16384块／2GiB临时盘。体素盒整体≤10000，超限不发布部分碰撞。`,`Full-source samples: ${settings.voxelSizeM}m is an explicit approximation, not the 0.03m default or point-cloud triangle reconstruction. 64³-cell spatial tiles, working set ≤${settings.maxOccupiedVoxels} cells; total ≤2M cells / 16384 tiles / 2GiB temporary disk. Boxes remain limited to 10000 globally; over-budget output is never partially published.`)}{settings.strategy==='triangle_mesh'&&<><br/>{tr('采样体素表面保留占据边界，仅适用Isaac静态三角拓扑（none）；MuJoCo不能等价消费，会明确拒绝，不自动换引擎。','Sample-voxel boundaries require Isaac static triangle topology (none). MuJoCo cannot consume them equivalently and must reject without switching engines.')}</>}</p>}
   <p className="lya-help">{tr('点云体素仅表示实际采样占据，未扫描墙面／净通道不作保证。显式三角面只有适用引擎才能保真消费，不自动切换引擎。','Point-cloud voxels describe measured sample occupancy; unscanned walls or passage clearance are not guaranteed. Explicit triangle meshes require a compatible engine; the engine is never switched automatically.')}</p>
   <div className="lya-row"><button type="button" disabled={blocked||!bindingAllowed} onClick={()=>void beginBind()}>{busy?tr('正在生成、绑定与同步…','Generating, binding and syncing…'):tr('生成并绑定真实碰撞','Generate and bind colliders')}</button><button type="button" onClick={openLibrary}>{tr('打开素材库','Open asset library')}</button></div>
   {!bindingAllowed&&<p className="lya-help">{tr('请在素材库为该资源完成适用的物理化；点云需显式选择点云物理化，空实体不能生成碰撞。','Complete the appropriate physicalization in the asset library. Point clouds need explicit physicalization; empty entities cannot generate colliders.')}</p>}
  </>}
  {busy&&facts.hasCollider&&<p className="lya-help" role="status">{tr('正在保存配置并核验当前物理帧…','Saving configuration and verifying the current physics frame…')}</p>}
  {busy&&bindingAbort.current&&<button type="button" onClick={()=>bindingAbort.current?.abort()}>{tr('停止本次碰撞生成','Stop this collider generation')}</button>}
  {progress&&<PhysicsProgressReadback value={progress} tr={tr}/>}
  {error&&<p className="lya-error lya-help" role="alert">{error}</p>}
 </fieldset>
}

const counterLabels:Record<string,[string,string]>={facesVisited:['已检查面','Faces visited'],samplesProcessed:['已处理采样','Samples processed'],sourcePoints:['原采样点','Source samples'],finitePoints:['有效采样点','Finite samples'],occupiedVoxels:['实际占据格','Occupied cells'],tilesProcessed:['已处理分块','Tiles processed'],totalTiles:['总分块','Total tiles'],temporaryBoxes:['合并前盒数','Boxes before merge'],boxesBeforeMerge:['合并前盒数','Boxes before merge'],boxesAfterMerge:['合并后盒数','Boxes after merge'],requiredBoxesAtLeast:['至少所需盒数','Minimum required boxes'],maxBoxes:['盒数预算','Box budget'],maxTotalBoxes:['整体盒数预算','Total box budget'],maxOccupiedVoxels:['占据工作集预算','Occupied-cell working limit'],requestedVoxelSizeM:['请求精度 m','Requested pitch m'],effectiveVoxelSizeM:['实际精度 m','Effective pitch m'],triangles:['三角面数','Triangles'],maxTriangles:['三角面预算','Triangle budget']}
export function PhysicsProgressReadback({value,tr}:{value:ResourcePhysicsProgress;tr:Translate}) {
 const facts=[value.progress?.facts,value.errorDetails,...value.pointCloud??[]].filter((item):item is Record<string,unknown>=>Boolean(item))
 const stages:Record<string,[string,string]>={'prepare':['准备碰撞','Preparing colliders'],'started':['开始几何计算','Geometry computation started'],'measure':['测量几何','Measuring geometry'],'voxel':['计算采样占据','Computing sample occupancy'],'complete':['本阶段完成','Stage complete'],'full-tiled-merge':['全域分块合并','Merging full-source tiles'],'full-tiled-verify':['校验全源覆盖','Verifying full-source coverage'],'full-spatial-tiles':['全域采样分块','Tiling full-source samples'],'voxel-surface':['生成采样体素表面','Generating sample-voxel boundaries']}
 return <div className="lya-help" data-testid="collider-progress" role="status"><strong>{value.status==='ok'?tr('资源派生完成，物理就绪仍需绑定与首帧','Resource derivation complete; binding and a first frame are still required'):value.status==='failed'?tr('派生失败，本次未发布碰撞','Derivation failed; this attempt did not publish colliders'):value.status==='skipped'?tr('此资源未选择碰撞生成','Collider derivation was not selected'):tr('正在处理资源','Processing resource')}</strong>{facts.map((item,index)=><p key={index}>{typeof item.stage==='string'&&(stages[item.stage]?tr(...stages[item.stage]!):tr('正在执行几何阶段','Running a geometry stage'))}{Object.entries(counterLabels).flatMap(([key,label])=>typeof item[key]==='number'?[<span key={key}> · {tr(...label)}：{String(item[key])}</span>]:[])}{typeof item.reason==='string'?<><br/>{item.reason}</>:null}{typeof item.coverageNotice==='string'?<><br/>{item.coverageNotice}</>:null}</p>)}{value.error&&<p>{value.error}</p>}</div>
}
