import {useEffect,useRef,useState} from 'react'
import type {PolicyLoadState} from '../../policy-registry/src/load-state.ts'
import type {WorldHandle} from '../../lyapunov-contracts/src/types.ts'
import type {Translate} from './entity-editor.tsx'
import {policyPanelAction,policyPrepareArgs,type PolicyPanelPorts} from './policy-panel-action.ts'
import {importLocalPolicy,type LocalPolicyImportReceipt} from './local-policy-import.ts'
import {localPolicyBundlePath,type LocalPolicyEntry} from '../../policy-registry/src/local-policy-file-contract.ts'
export {policyPanelAction,policyPrepareArgs} from './policy-panel-action.ts'
export type {PolicyPanelPorts} from './policy-panel-action.ts'
export interface PolicySourceRow {adapterId:string;packId?:string;label:string;identity:{provider:string;modelId:string;revision:string};files:string[];downloadModelId:string|null;fallback?:{urls?:Array<{path:string;url:string}>;directories?:Array<{path:string;url:string}>}}
export const policyCategoryLabels:Record<PolicyLoadState['category'],string>={direct_execution:'执行路线已登记（实例状态另核）',weights_need_adapter:'有权重，来源或实例待准备',missing_files_or_runtime:'缺文件、运行依赖或世界绑定',model_incompatible:'当前模型不兼容'}
export function PolicyLibraryPanel({available,canLoad,canRegister=true,canLoadAsset=canLoad,sceneId,entityId,worldId,worldStatus,expectedGeneration,expectedRevision,command,chooseFile,onActivated,onAssetLoaded,importReceipt,tr}:{available:boolean;canLoad:boolean;canRegister?:boolean;canLoadAsset?:boolean;sceneId?:string;entityId?:string;worldId?:string;worldStatus?:WorldHandle['status'];expectedGeneration?:number;expectedRevision?:number;command:PolicyPanelPorts['command'];chooseFile?:()=>Promise<string|undefined>;onActivated?:(result:any)=>void;onAssetLoaded?:(modelPath:string,downloadModelId:string,provenance:Record<string,unknown>)=>Promise<void>;importReceipt?:LocalPolicyImportReceipt;tr:Translate}){
 const [kind,setKind]=useState<'policy'|'vla'>('policy'),[path,setPath]=useState(importReceipt?.filePath??''),[rows,setRows]=useState<PolicySourceRow[]>([]),[sourceId,setSourceId]=useState(''),[installedIdentity,setInstalledIdentity]=useState<PolicySourceRow['identity']|undefined>(importReceipt?.face.identity),[state,setState]=useState<PolicyLoadState|undefined>(importReceipt?.face.state),[failure,setFailure]=useState<any>(importReceipt?.face.failure),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [localEntries,setLocalEntries]=useState<LocalPolicyEntry[]>(importReceipt?.entry?[importReceipt.entry]:[]),[localId,setLocalId]=useState(importReceipt?.entry?.id??'')
 const serial=useRef(0),alive=useRef(true)
 useEffect(()=>()=>{alive.current=false;serial.current++},[])
 useEffect(()=>{if(!available)return;let current=true;void command('policy_download_sources',{}).then(result=>{if(!current)return;setRows(Array.isArray(result.models)?result.models:[]);setLocalEntries(Array.isArray(result.localEntries)?result.localEntries:[])}).catch(error=>{if(current)setError(String(error))});return()=>{current=false}},[available])
 useEffect(()=>{serial.current++;setBusy(false);setState(undefined);setFailure(undefined)},[sceneId,entityId,worldId,worldStatus,expectedGeneration,expectedRevision])
 useEffect(()=>{if(!importReceipt)return;serial.current++;setBusy(false);setError('');setPath(importReceipt.filePath);setKind('policy');setState(importReceipt.face.state);setFailure(importReceipt.face.failure);setInstalledIdentity(importReceipt.face.identity);if(importReceipt.entry){setLocalId(importReceipt.entry.id);setLocalEntries(rows=>[importReceipt.entry!,...rows.filter(row=>row.id!==importReceipt.entry!.id)])}},[importReceipt])
 const selected=rows.find(row=>row.adapterId===sourceId),identity=installedIdentity??selected?.identity
 const context={kind,...sceneId?{sceneId,expectedRevision}:{},...entityId?{entityId}:{},...worldId?{worldId,expectedGeneration}:{}}
 const input=()=>({...context,...localId?{entryId:localId}:path.trim()?(localPolicyBundlePath(path.trim())?{manifestPath:path.trim()}:{filePath:path.trim()}):{},...identity?{identity}:{},...state?.localSource?{localSource:state.localSource}:{}})
 const run=async(task:(current:()=>boolean)=>Promise<any>)=>{const request=++serial.current,current=()=>alive.current&&request===serial.current;setBusy(true);setState(undefined);setError('');setFailure(undefined);try{const result=await task(current);if(!current())return;if(result.state)setState(result.state);if(result.failure)setFailure(result.failure);if(result.identity)setInstalledIdentity(result.identity);if(result.entry){setPath('');setLocalId(result.entry.id);setSourceId('');setInstalledIdentity(result.entry.identity);setLocalEntries(rows=>[result.entry,...rows.filter(row=>row.id!==result.entry.id)])}if(result.result?.world&&result.result?.snapshot)onActivated?.(result.result)}catch(error){if(current())setError(String(error))}finally{if(current())setBusy(false)}}
 const action=(value:'check'|'load'|'download'|'prepare'|'activate')=>run(async current=>value==='load'&&!localId?(await importLocalPolicy({command,current},path.trim(),{...context,...identity?{identity}:{}})).face:policyPanelAction({command,current},value,value==='download'?{...context,modelId:selected?.downloadModelId}:input()))
 const loadAsset=()=>run(async current=>{const id=selected?.downloadModelId;if(!id)return {};const result=await policyPanelAction({command,current},'asset',{modelId:id});if(current()&&result.result?.status==='ASSET_DOWNLOADED'&&typeof result.result.modelPath==='string'&&onAssetLoaded)await onAssetLoaded(result.result.modelPath,id,{packId:selected?.packId??id,downloadModelId:id,source:result.result.source,assetModel:result.result.assetModel,assetBytesVerified:result.result.assetBytesVerified,fullBundleReady:result.result.fullBundleReady,policyPrepared:false});return result})
 return <fieldset className="lya-robot-card" data-testid="robot-policy-vla-library"><legend>{tr('策略 / VLA','Policy / VLA')}</legend>
  <p className="lya-help">{tr('原生关节和夹爪控制无需训练策略。拖入权重、bundle.json 或完整目录即可登记到本地策略库，无需先选机器人。准备、兼容与应用按所选实例分别预检。','Native joints and grippers need no trained policy. Drop weights, bundle.json or a complete directory to register locally before choosing a robot. Preparation, compatibility and application use the selected instance.')}</p>
  {!entityId&&<p className="lya-help">{tr('选择当前场景机器人实例后可核对本体与世界兼容性。','Select a robot instance to check compatibility with its world.')}</p>}
  <div className="lya-segment"><button aria-pressed={kind==='policy'} onClick={()=>{setKind('policy');setState(undefined);setInstalledIdentity(undefined)}}>{tr('控制策略','Policy')}</button><button aria-pressed={kind==='vla'} onClick={()=>{setKind('vla');setSourceId('');setInstalledIdentity(undefined);setState(undefined)}}>VLA</button></div>
  <label className="lya-field-label">{tr('本地权重 / bundle.json / 完整目录','Local weights / bundle.json / complete directory')}<input className="lya-wide" value={path} onChange={e=>{setPath(e.target.value);setLocalId('');setInstalledIdentity(undefined);setState(undefined)}} placeholder={tr('目录只读取根 bundle.json；不递归搜索','Directories use root bundle.json; no recursive search')}/></label>
  <div className="lya-row">{chooseFile&&<button data-policy-register="choose" disabled={!available||!canRegister||busy} onClick={()=>void run(async current=>{const chosen=await chooseFile();if(chosen&&current()){setPath(chosen);setLocalId('');setInstalledIdentity(undefined);return (await importLocalPolicy({command,current},chosen,{...context,...selected?.identity?{identity:selected.identity}:{}})).face}return {}})}>{tr('选择并登记文件','Choose and register file')}</button>}<button data-policy-register="path" disabled={!available||!canRegister||busy||!path.trim()&&!localId} onClick={()=>void action('load')}>{localId?tr('读取已登记策略','Read registered policy'):tr('登记本地文件 / 目录','Register local file / directory')}</button><button disabled={!available||busy} onClick={()=>void action('check')}>{busy?tr('检查中…','Checking…'):tr('检查状态 / 兼容','Check status / compatibility')}</button></div>
  <div data-testid="policy-local-library"><label className="lya-field-label">{tr('本地已登记策略','Registered local policies')}<select className="lya-wide" value={localId} aria-label={tr('本地已登记策略','Registered local policies')} onChange={event=>{const entry=localEntries.find(row=>row.id===event.target.value);setLocalId(event.target.value);setPath('');setInstalledIdentity(entry?.identity);setSourceId('');setState(undefined);setFailure(undefined)}}><option value="">{tr('选择已登记原件；不会自动应用','Choose registered bytes; no automatic application')}</option>{localEntries.map(entry=><option key={entry.id} value={entry.id}>{entry.label} · {entry.available?(entry.identity?tr('固定来源','Pinned source'):tr('来源与接口待验证','Source and interfaces unverified')):tr('缓存原件缺失','Cached bytes missing')}</option>)}</select></label></div>
  {importReceipt?.entry&&<p className="lya-help" data-testid="policy-registration-receipt">{tr('已登记到本地策略库，重开可读取；机器人应用尚未执行。','Registered in the local library and available after reopening; robot application has not run.')}</p>}
  {state?.category==='weights_need_adapter'&&path&&!localPolicyBundlePath(path)&&<p className="lya-help" data-testid="policy-bundle-required">{state.localSource?.bundlePath?tr('已登记包根：','Registered bundle root: '):tr('请选择实际完整bundle或明确已登记来源；未扫描目录，也未猜测附近文件。','Choose a complete bundle or a registered source; directories and nearby files were not searched.')}<code>{state.localSource?.bundlePath??''}</code> · {tr('已实现适配器与本实例准备是不同状态。','Implemented adapters and preparation on this instance are separate states.')}</p>}
  {state?.localSource&&<p className="lya-help" data-testid="policy-local-source">{tr('本地来源：','Local source: ')}{state.localSource.status} · {state.localSource.adapterId??tr('未识别固定来源','Fixed source unidentified')} · {tr('准备入口：','Preparation: ')}{state.localSource.prepareFrom}{state.localSource.licenseUnchecked||state.localSource.missingLicense?.length?` · ${tr('完整包分发许可未核；明确本地权重采纳单独判断','Bundle distribution license unchecked; explicit local weights are assessed separately')}`:''}</p>}
  {kind==='policy'&&<><button disabled={!available||busy} onClick={()=>void run(async current=>{const result=await command('policy_download_sources',{});if(current()){setRows(Array.isArray(result.models)?result.models:[]);setLocalEntries(Array.isArray(result.localEntries)?result.localEntries:[])}return {}})}>{tr('刷新本地库 / 已登记来源','Refresh local library / registered sources')}</button><select className="lya-wide" aria-label={tr('已登记策略来源','Registered policy source')} value={sourceId} onChange={e=>{setSourceId(e.target.value);setInstalledIdentity(undefined);setState(undefined)}}><option value="">{tr('选择固定来源，不自动下载','Choose a source; no automatic download')}</option>{rows.map(row=><option key={row.adapterId} value={row.adapterId}>{row.label}</option>)}</select>
   {selected&&<p className="lya-help">{selected.identity.modelId} · {selected.identity.revision.slice(0,12)} · {tr('本地执行，完整依赖预检','Local execution with dependency preflight')}</p>}
   <div className="lya-row"><button disabled={!available||!canLoadAsset||!sceneId||busy||!selected?.downloadModelId||!onAssetLoaded} onClick={()=>void loadAsset()}>{tr('仅下载本体并载入','Download body and load')}</button><button disabled={!available||!canLoad||busy||!selected?.downloadModelId} onClick={()=>void action('download')}>{tr('下载已登记完整包','Download registered bundle')}</button><button disabled={!available||!canLoad||!entityId||busy||!identity} onClick={()=>void action('prepare')}>{tr('准备已登记适配器','Prepare registered adapter')}</button></div>
   <p className="lya-help">{tr('本体只取已核许可的XML与依赖，并登记到当前Scene/Resource；完整包、策略许可、适配器和世界执行各自预检。','Body files use their verified license and are registered in Scene/Resource; the policy bundle, adapter and world are checked separately.')}</p>
   <button disabled={!available||!canLoad||busy||!identity||!entityId||!worldId||!state?.policyPrepared} onClick={()=>void action('activate')}>{tr('应用到所选实例 / 建立匹配世界','Apply to this instance / create matched world')}</button><p className="lya-help">{tr('该操作会先核同本体与当前引擎，停止并重建所选世界为策略固定步长；不改已保存引擎偏好、不执行行走。','This checks model and engine, stops and recreates the selected world with policy timing. It preserves engine preference and does not execute walking.')}</p>
   {selected&&!selected.downloadModelId&&<p className="lya-help">{tr('该来源尚无统一下载包入口；按下面固定文件来源取件，不能猜测下载型号。','No unified bundle endpoint for this source; use its exact files below.')}</p>}
  </>}
  {kind==='vla'&&<p className="lya-help">{tr('当前机器人没有通用可执行VLA适配器。已存在权重仍需图像/状态观测、动作维度/单位及本体控制映射；加载不会启动远程推理。','There is no generic VLA executor for this robot. Weights still require observation and action mappings; loading never starts remote inference.')}</p>}
  {state&&<div role="status" data-policy-category={state.category}><strong>{policyCategoryLabels[state.category]}</strong><p className="lya-help">{state.ready?tr('预检通过；运动成功仍需真实执行回执。','Preflight passed; motion still needs execution evidence.'):tr('尚不可执行；请一次处理下面缺项。','Execution is blocked; resolve the items below.')} · {tr('观测 / 动作 / 当前关节：','Observation / action / current joints: ')}{state.dimensions.observation??'—'} / {state.dimensions.action??'—'} / {state.dimensions.currentJointCount??'—'}</p>{state.missing.map((item,i)=><p className="lya-help" key={i}><code>{item.code}</code> · {item.field}：{item.detail}</p>)}{state.nextActions.map((item,i)=><p className="lya-help" key={i}>{item.label}</p>)}</div>}
  {state&&state.executionKind!=='native_control'&&<p className="lya-help" data-testid="policy-execution-evidence">{tr('本地适配：','Local preparation: ')}{state.policyPrepared?tr('已有已验适配信息','Verified adapter metadata exists'):tr('未准备','Not prepared')} · {tr('运行依赖：','Runtime dependencies: ')}{state.runtimeChecked&&!state.missing.some(m=>m.code.startsWith('RUNTIME_'))?tr('预检满足','Preflight satisfied'):tr('未满足或未核','Missing or unchecked')} · {tr('实际推理与稳定行走以运行回执判定；此状态检查没有完成稳定行走验收。','Actual inference and stable walking require execution evidence; this state check has not accepted stable walking.')}</p>}
  {state?.runtime&&<div className="lya-help" data-testid="policy-runtime-selection">
   <p>{tr('策略运行环境：','Policy runtime: ')}{state.runtime.status==='AVAILABLE'?`${state.runtime.provider} / ${state.runtime.source} · ${state.runtime.python}`:tr('已登记解释器没有满足所需依赖','Registered interpreters do not satisfy the required modules')}</p>
   <p>{tr('当前来源所需模块：','Required modules for this source: ')}{state.runtime.requiredModules.join(' / ')} · {tr('CPU 模式；选择解释器不启动物理引擎','CPU mode; interpreter selection does not start physics')}</p>
   {state.runtime.status==='AVAILABLE'?<p>{Object.entries(state.runtime.versions).map(([name,version])=>`${name} ${version}`).join(' · ')}</p>:<><p>{state.runtime.prepare?.detail}</p><p>{tr('设置 → 物理引擎 → 策略 CPU 独立环境，可安装/修复；ONNX 依赖由 MuJoCo 安装提供。','Settings → Physics engines → Independent policy CPU environment for install/repair; MuJoCo supplies ONNX dependencies.')}</p><code>{state.runtime.prepare?.command}</code></>}
  </div>}
  {state?.evidence&&<div className="lya-help" data-testid="policy-state-layers">
   <p>{tr('本体与缓存：','Robot and cache: ')}{tr('当前场景本体','Robot in this scene')}={state.evidence.robotPresent?tr('存在','present'):tr('未选实例或未核','no instance or unchecked')} · {tr('完整包字节已验','Complete bundle verified')}={state.evidence.completeBundleVerified?tr('是','yes'):tr('未核','unchecked')} · {tr('权重存在 / 字节已验','Weights present / verified')}={[state.evidence.weightsPresent,state.evidence.weightsVerified].map(v=>v?tr('是','yes'):tr('未核','unchecked')).join(' / ')}</p>
   <p>{tr('适配与实例：','Adapter and instance: ')}{tr('代码已实现 / 缓存已准备 / 本实例已匹配 / 运行依赖','Implemented / prepared cache / matched instance / runtime')}={[state.evidence.adapterImplemented,state.evidence.cachePrepared,state.evidence.preparedOnInstance,state.evidence.runtimeReady].map(v=>v?tr('是','yes'):tr('未核或未满足','missing or unchecked')).join(' / ')}</p>
   <p>{tr('世界匹配 / 世界正在运行','World matched / world running')}={[state.evidence.worldMatched,state.evidence.worldRunning].map(v=>v?tr('是','yes'):tr('否或未核','no or unchecked')).join(' / ')}{state.world?` · ${state.world.status} · ${tr('代次 / 场景版本','Generation / scene revision')} ${state.world.worldGeneration} / ${state.world.appliedSceneRevision}`:''} · {tr('行为验收：未由此检查证明','Behavior: not verified by this check')}</p>
  </div>}
  {failure&&<p className="lya-error" role="alert">{failure.code}：{failure.message} · {tr('已立即停止，未自动重试。','Stopped immediately; no automatic retry.')}</p>}
  {failure?.missingFiles?.length>0&&<p className="lya-error">{tr('缺文件：','Missing files: ')}{failure.missingFiles.join('、')}</p>}{failure?.missingLicense?.length>0&&<p className="lya-error">{tr('许可未核：','License unchecked: ')}{failure.missingLicense.join('、')} · {tr('补齐许可前不取件；固定来源链接仅供核对。','Resolve the license before fetching; fixed source links are for verification.')}</p>}
  {(failure?.fallback||selected?.fallback)&&<details open={Boolean(failure)}><summary>{tr('准确来源 web_fetch 回退','Exact source web_fetch fallback')}</summary><p className="lya-help">{failure?.missingLicense?.length?tr('先核所列许可。来源固定，不能通过另一包或另一revision绕过阻断。','Verify the listed license first; another bundle or revision cannot bypass this block.'):tr('端点首错误后按固定revision取明确文件，不重复本地搜索或整仓下载。','On the first endpoint error, fetch exact files at the fixed revision.')}</p>{((failure?.fallback??selected?.fallback)?.urls??[]).map((row:any)=><p className="lya-help" key={row.path}><a href={row.url} target="_blank" rel="noreferrer">{row.path}</a></p>)}{((failure?.fallback??selected?.fallback)?.directories??[]).map((row:any)=><p className="lya-help" key={row.path}>{tr('声明依赖目录：','Declared dependency directory: ')}<a href={row.url} target="_blank" rel="noreferrer">{row.path}</a></p>)}</details>}
  {error&&<p className="lya-error" role="alert">{error}</p>}
 </fieldset>
}
