import {useState,useSyncExternalStore} from 'react'
import type {SettingsScope} from '@deepseek-ai/dsh-client-ui-settings/client'
import {workspaceDefaults,workspaceActions,validateWorkspaceShortcuts,type WorkspacePreferences,type WorkspaceAction} from './preferences.ts'
export const workspaceActionLabels:Record<WorkspaceAction,[string,string]>={fileOpen:['打开文件','Open file'],panelClose:['关闭面板','Close panel'],terminalToggle:['显示/收起终端','Toggle terminal'],reviewToggle:['显示/收起Review','Toggle Review'],fileTreeToggle:['显示/收起文件树','Toggle file tree'],terminalNew:['新终端','New terminal'],addSelection:['添加选区到上下文','Add selection to context'],worktreeNew:['打开新Worktree','Open new worktree']}
export function WorkspacePreferencesSection({scope,tr}:{scope:SettingsScope<WorkspacePreferences>;tr:(zh:string,en:string)=>string}){
 const state=useSyncExternalStore(listener=>scope.subscribe(listener),()=>scope.getSnapshot(),()=>scope.getSnapshot()),preferences=state.value??workspaceDefaults,[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<WorkspacePreferences>()
 const value=editing??preferences,set=(field:string,v:unknown)=>setEditing({...value,[field]:v})
 const save=async(reset=false)=>{setBusy(true);setError('');try{if(reset)await scope.mutate(Object.keys(workspaceDefaults).map(key=>({op:'unset' as const,path:[key]})));else{const next={...value,shortcuts:validateWorkspaceShortcuts(value.shortcuts)};await scope.mutate(Object.entries(next).map(([key,value])=>({op:'set' as const,path:[key],value})));}setEditing(undefined)}catch(error){setError(String(error))}finally{setBusy(false)}}
 return <section aria-label={tr('文件与终端偏好','Files and terminal preferences')} style={{padding:20,display:'grid',gap:12}}><h2>{tr('文件与终端','Files and terminal')}</h2><fieldset disabled={state.status!=='ready'||!state.writable||busy} style={{display:'grid',gap:12}}>
 <label><input type="checkbox" checked={value.autoSave} onChange={e=>set('autoSave',e.target.checked)}/>{tr('自动保存编辑内容','Automatically save edits')}</label>
 <label>{tr('停止输入后保存（毫秒）','Save after typing stops (ms)')}<input type="number" min={250} max={10000} value={value.autoSaveDelayMs} onChange={e=>set('autoSaveDelayMs',Number(e.target.value))}/></label>
 {(['editor','terminal'] as const).map(kind=><div key={kind}><label>{tr(kind==='editor'?'编辑器字体族':'终端字体族',kind==='editor'?'Editor font family':'Terminal font family')}<input value={value[`${kind}FontFamily`]} onChange={e=>set(`${kind}FontFamily`,e.target.value)} placeholder={tr('系统等宽字体','System monospace')}/></label><label>{tr('字号','Size')}<input type="number" min={10} max={28} value={value[`${kind}FontSize`]} onChange={e=>set(`${kind}FontSize`,Number(e.target.value))}/></label></div>)}
 <p>{tr('自动保存使用文件版本校验。发生外部修改冲突时保留草稿并停止重试；可先复制草稿再重新读取磁盘。字体名称使用系统已安装字体。','Autosave checks the file version. External changes keep the draft and stop retries. Copy your draft before reloading from disk. Font names use fonts installed on the system.')}</p>
 {workspaceActions.map(action=><label key={action}>{tr(...workspaceActionLabels[action])}<input aria-label={tr(...workspaceActionLabels[action])} value={value.shortcuts[action]} onChange={e=>set('shortcuts',{...value.shortcuts,[action]:e.target.value})}/></label>)}
 <p>{tr('mod表示Ctrl/Cmd；多个绑定用逗号分隔，backquote/反引号与backslash/反斜杠使用按键位置。空值禁用。','mod means Ctrl/Cmd; separate alternatives with commas. Backquote and backslash use their key positions. Leave empty to disable.')}</p>
 <div><button disabled={!editing} onClick={()=>void save()}>{tr('保存工作区偏好','Save workspace preferences')}</button><button onClick={()=>void save(true)}>{tr('恢复默认','Reset defaults')}</button></div></fieldset>{state.status!=='ready'&&<p role="status">{tr('等待原生设置连接。','Waiting for native settings.')}</p>}{error&&<p role="alert">{error}</p>}</section>
}
